WebApplication3/Models/HotellerieModel/Hotel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.Models.HotellerieModel
{
    public class Hotel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "champ obligatoire")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "longueur entre 3 et 20")]
        public string Nom { get; set; } = null!;

        [Range(1, 5, ErrorMessage = "valeur comprise entre 1 et 5")]
        public int Etoiles { get; set; }

        [Required(ErrorMessage = "champ obligatoire")]
        public string Ville { get; set; } = null!;

        [Required, Url(ErrorMessage = "URL non valide"), Display(Name = "Site Web")]
        public string SiteWeb { get; set; } = null!;

        public int Tel { get; set; }
        public virtual ICollection<Appreciation> Appreciations { get; set; }
    }
}

WebApplication3/Controllers/AppreciationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Models.HotellerieModel;

namespace WebApplication3.Controllers
{
    public class AppreciationsController : Controller
    {
        private readonly HotellerieDbContext _context;

        public AppreciationsController(HotellerieDbContext context)
        {
            _context = context;
        }

        // GET: Appreciations
        public async Task<IActionResult> Index()
        {
            var hotellerieDbContext = _context.Appreciations.Include(a => a.Hotel);
            return View(await hotellerieDbContext.ToListAsync());
        }

        // GET: Appreciations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appreciation = await _context.Appreciations
                .Include(a => a.Hotel)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appreciation == null)
            {
                return NotFound();
            }

            return View(appreciation);
        }

        // GET: Appreciations/Create
        public IActionResult Create()
        {
            ViewData["HotelId"] = new SelectList(_context.Hotels, "Id", "Nom");
            return View();
        }

        // POST: Appreciations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomPers,Commentaire,HotelId")] Appreciation appreciation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appreciation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HotelId"] = new SelectList(_context.Hotels, "Id", "Nom", appreciation.HotelId);
            return View(appreciation);
        }

        // GET: Appreciations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appreciation = await _context.Appreciations.FindAsync(id);
            if (appreciation == null)
            {
                return NotFound();
            }
            ViewData["HotelId"] = new SelectList(_context.Hotels, "Id", "Nom", appreciation.HotelId);
            return View(appreciation);
        }

        // POST: Appreciations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomPers,Commentaire,HotelId")] Appreciation appreciation)
        {
            if (id != appreciation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appreciation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppreciationExists(appreciation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HotelId"] = new SelectList(_context.Hotels, "Id", "Nom", appreciation.HotelId);
            return View(appreciation);
        }

        // GET: Appreciations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appreciation = await _context.Appreciations
                .Include(a => a.Hotel)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appreciation == null)
            {
                return NotFound();
            }

            return View(appreciation);
        }

        // POST: Appreciations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appreciation = await _context.Appreciations.FindAsync(id);
            if (appreciation != null)
            {
                _context.Appreciations.Remove(appreciation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppreciationExists(int id)
        {
            return _context.Appreciations.Any(e => e.Id == id);
        }
    }
}

WebApplication3/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3.Models.HotellerieModel;

namespace WebApplication3.Controllers
{
    public class HotelsController : Controller
    {
        private readonly HotellerieDbContext _context;

        public HotelsController(HotellerieDbContext context)
        {
            _context = context;
        }

        // GET: Hotels
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hotels.ToListAsync());
        }

        // GET: Hotels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        // GET: Hotels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Etoiles,Ville,SiteWeb,Tel")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hotel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hotel);
        }

        // GET: Hotels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels.FindAsync(id);
            if (hotel == null)
            {
                return NotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Etoiles,Ville,SiteWeb,Tel")] Hotel hotel)
        {
            if (id != hotel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hotel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HotelExists(hotel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hotel = await _context.Hotels.FindAsync(id);
            if (hotel != null)
            {
                _context.Hotels.Remove(hotel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HotelExists(int id)
        {
            return _context.Hotels.Any(e => e.Id == id);
        }
    }
}

WebApplication3/Views/Hotels/Create.cshtml
@model WebApplication3.Models.HotellerieModel.Hotel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etoiles" class="control-label"></label>
                <input asp-for="Etoiles" class="form-control" />
                <span asp-validation-for="Etoiles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ville" class="control-label"></label>
                <input asp-for="Ville" class="form-control" />
                <span asp-validation-for="Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiteWeb" class="control-label"></label>
                <input asp-for="SiteWeb" class="form-control" />
                <span asp-validation-for="SiteWeb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication3/Views/Hotels/Delete.cshtml
@model WebApplication3.Models.HotellerieModel.Hotel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etoiles)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etoiles)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ville)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ville)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiteWeb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiteWeb)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication3/Views/Hotels/Details.cshtml
@model WebApplication3.Models.HotellerieModel.Hotel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Etoiles)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Etoiles)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ville)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ville)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SiteWeb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SiteWeb)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication3/Views/Hotels/Edit.cshtml
@model WebApplication3.Models.HotellerieModel.Hotel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Hotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Etoiles" class="control-label"></label>
                <input asp-for="Etoiles" class="form-control" />
                <span asp-validation-for="Etoiles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ville" class="control-label"></label>
                <input asp-for="Ville" class="form-control" />
                <span asp-validation-for="Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiteWeb" class="control-label"></label>
                <input asp-for="SiteWeb" class="form-control" />
                <span asp-validation-for="SiteWeb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication3/Views/Hotels/Index.cshtml
@model IEnumerable<WebApplication3.Models.HotellerieModel.Hotel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-action="Index" asp-controller="Appreciations">Appreciations</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Etoiles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ville)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SiteWeb)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Etoiles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ville)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SiteWeb)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tel)
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>